import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";
import {FcGoogle} from 'react-icons/fc/index'

import { trpc } from "../utils/trpc";
import { useRouter } from "next/router";

const Home: NextPage = () => {

  const {data: session} = useSession();
  const router = useRouter()

  if(session) {
    router.push('/admin')
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta key={1} charSet="UTF-8"/>
        <meta key={2} httpEquiv="X-UA-Compatible" content="IE=edge"/>
        <meta key={3} name="viewport" content="width=device-width, initial-scale=1.0"/>
        <meta key={4} name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="max-w-md mx-auto flex flex-col items-center justify-center gap-8 p-6">
        <div className="ml-6 pt-1">
          <h1 className="text-xl text-gray-100 leading-tight">Login with Google</h1>
        </div>
        <button onClick={() => signIn('google', {callbackUrl: "/admin"})} className="w-full flex gap-2 items-center justify-center mx-2 px-4 py-2 rounded-full bg-green-300">
          <p>Sign In</p>
          <FcGoogle className="text-xl"/> 
        </button>
      </div>

      
    </>
  );
};

export default Home;


